name: Build Atmosphere

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo wget https://apt.devkitpro.org/install-devkitpro-pacman
        sudo chmod +x ./install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo /opt/devkitpro/pacman/bin/dkp-pacman -S switch-dev switch-glm switch-libjpeg-turbo devkitARM devkitarm-rules hactool
        pip install lz4 PyCryptodome

    - name: Clone Atmosphere repository
      run: git clone https://github.com/Atmosphere-NX/Atmosphere.git

    - name: Build Atmosphere
      run: cd Atmosphere && make
